apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: twfeel
  namespace: demo

spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: twfeel
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          container:
            image: gcr.io/s9-demo/twfeel:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.1.21"
            - name: GIN_MODE
              value: "release"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twfeel-secrets
                  key: ACCESS_TOKEN
            - name: T_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: twfeel-secrets
                  key: T_CONSUMER_KEY
            - name: T_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: twfeel-secrets
                  key: T_CONSUMER_SECRET
            - name: T_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twfeel-secrets
                  key: T_ACCESS_TOKEN
            - name: T_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: twfeel-secrets
                  key: T_ACCESS_SECRET
